In [1]:
#2 NumPy Operations

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# About arithmetic. You can easily perform array-of-array arithmetic
# or scalar-of-array arithmetic (where a scalar number is just 
# a single value number) eg.

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# so, it does the addition on element-by-element basis, based off
# their index position eg. adds index 0s togethe, index 1s together,
# so here, it just doubles every number. You can also eg multiply
#element by element, so now every number is, basically, squared:

In [9]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
# Subtraction: 
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# A quick note on division - eg. arr/arr. If you have a zero, 
#you'll get a warning ('invalid value encountered in true divide.')
# as it doesn't really make sense dividing something by zero. It still
# returns a value instead of 'giving a true error' and stopping the program - 
# but you'll get a warning. Nan = non-applicable value.

In [12]:
arr/arr

/Users/dmitry/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
# if you divide 1 by zero - 1/arr - you'll also get a warning, but 
# with another first value, inf for infinity, because the closest
# to dividing 1 by zero is infinity. 

In [14]:
1/arr


/Users/dmitry/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [17]:
# Lastly, you can do exponentials. you can do anything with scalars,
arr ** 3 
# arr to the power of three. He had 'dtype?int32' at the end.

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [18]:
# and if you want to add the number 100 to everything in your array
# Basically, what this means is it will broadcast this (100) to 
# every single element in arr, and this is going to be very useful
# later on. 
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [19]:
#Now, not all mathematical functions are as simple. Numpy comes
# with many universal array functions - SEE Jupyter notebook for 
# a link to the documentation on this. They're simply mathematical
# operations that you can use to perform the operation across every
# element in the array. Some really common ones include: 

In [20]:
# taking the square root of everything in the array. 
#Hit np. and tab to see a bunch of methods included in the list.
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [21]:
# the exponential, e to the power of everything in the array.
# Find out - what's the +00 part?
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [22]:
# find the maximum value in the array
np.max(arr)

9

In [23]:
#As we saw earlier, we can just call this 
#as a method off the array. What's interesting, under the hood, 
# is that when you call this method, you're really just calling 
# this universal array function. It's just a different way 
# of calling it.

In [24]:
arr.max()

9

In [25]:
# and you can do the same for any mathematical function you 
# can think of, it's available.

In [26]:
# eg the sin of everything in the array
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [28]:
# or, the log of everything in the array. Just keep in mind, 
# if you have a zero - it doesn't really make sense to take 
# the log of zero - you'll get a warning, eg negative of infinity.
np.log(arr)

/Users/dmitry/.local/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [29]:
#Ok, that's it - some of the more common ones will show up later 
# in this course.